para:
  train_dataset_length : 1600000
  test_dataset_length : 100000
  train_batch_size: 160
  test_batch_size: 2000
  lr: 0.001
  seed: 1
  log_interval: 1
  num_permu: 128
  num_permu_list: "128"
  epoch_szie : 200

  # Use in train validate data util
  snr: 5

  # Use in test_ber
  snr_list: 1,2,3,4,5,6
  Boosting_number_list: "1"

  data_type: "127_64"
  logger_name: RM{}_p=128
  CUDA_VISIBLE_DEVICES: "0"
  train_save_path: ./save/RM_{}/p=128/RM_{}_{}.pth
  test_model_path: ./save/RM_{}/p=128/

data:
  v_size: None # dont edit, will init
  e_size: None # dont edit, will init
  l_size: None # dont edit, will init
  rate: None   # dont edit, will init
  pos : None # dont edit, will init
  H : None # dont edit, will init
  G : None # dont edit, will init
  perma: None # dont edit, will init
  H_path: ./data/rmdata/RM_{}/RM_H_{}.txt
  G_path: ./data/rmdata/RM_{}/RM_G_{}.txt
  perma_path: ./data/rmdata/RM_{}/GFpermutation.txt
